"""Per-section feature scoring.

Every score is computed from real stored data (professor ratings, historical
grades, meeting times) -- nothing here is estimated or generated by an LLM.
A dimension only contributes to the Fit Score when it is both `requested`
(the student asked about it, or it's a default always-shown dimension) and
has real data behind it; otherwise it's surfaced as "missing", never guessed.
"""

from dataclasses import dataclass

from app.analytics.grade_stats import GradeDistributionStats
from app.models.assessment import AssessmentMetadata
from app.models.section import Section
from app.schemas.ai_search import ParsedRequirement


@dataclass
class DimensionResult:
    score: float | None
    requested: bool
    detail: str


def _professor_rating(section: Section) -> DimensionResult:
    rating = section.professor.rating if section.professor else None
    if rating is None:
        return DimensionResult(None, True, "No professor rating data is available.")
    score = (rating.overall_rating / 5) * 100
    return DimensionResult(
        score, True, f"Professor rating is {rating.overall_rating:.1f}/5."
    )


def _historical_grades(stats: GradeDistributionStats | None) -> DimensionResult:
    if stats is None or stats.mean_gpa is None:
        return DimensionResult(
            None, True, "No historical grade data is available for this course/professor combination."
        )
    score = (stats.mean_gpa / 4.0) * 100
    return DimensionResult(
        score,
        True,
        f"Historical mean GPA is {stats.mean_gpa:.2f} across {stats.total_students} recorded students.",
    )


def _delivery_mode_preference(section: Section, parsed: ParsedRequirement) -> DimensionResult:
    preferred = parsed.soft_preferences.prefer_delivery_modes
    mode = section.delivery_mode.value
    if preferred:
        if mode == preferred[0]:
            return DimensionResult(100.0, True, f"Delivery mode ({mode}) is your top preference.")
        if mode in preferred:
            return DimensionResult(70.0, True, f"Delivery mode ({mode}) is one of your preferences.")
        return DimensionResult(40.0, True, f"Delivery mode ({mode}) isn't among your stated preferences.")
    if parsed.hard_constraints.delivery_modes:
        return DimensionResult(100.0, True, f"Delivery mode ({mode}) matches your requirement.")
    return DimensionResult(None, False, "No delivery mode preference specified.")


def _grading_ease(section: Section, parsed: ParsedRequirement) -> DimensionResult:
    if not parsed.soft_preferences.prefer_easier_grading:
        return DimensionResult(None, False, "Grading-ease preference not specified.")
    difficulty = (
        section.professor.rating.difficulty_rating
        if section.professor and section.professor.rating
        else None
    )
    if difficulty is None:
        return DimensionResult(None, True, "No professor difficulty rating is available.")
    score = ((5 - difficulty) / 5) * 100
    return DimensionResult(score, True, f"Professor difficulty is rated {difficulty:.1f}/5 (lower is easier).")


def _campus_days(section: Section, parsed: ParsedRequirement) -> DimensionResult:
    if not parsed.soft_preferences.prefer_fewer_campus_days:
        return DimensionResult(None, False, "Campus-days preference not specified.")
    distinct_days = len({m.day_of_week.value for m in section.meetings})
    if distinct_days <= 1:
        return DimensionResult(100.0, True, f"Meets on campus {distinct_days} day(s) per week.")
    if distinct_days == 2:
        return DimensionResult(70.0, True, "Meets on campus 2 days per week.")
    return DimensionResult(40.0, True, f"Meets on campus {distinct_days} days per week.")


_EXAM_FORMAT_SCORES = {"online": 100.0, "take_home": 80.0, "none": 70.0, "in_person": 30.0}


def _exam_preference(assessment: AssessmentMetadata | None, parsed: ParsedRequirement) -> DimensionResult:
    if not parsed.soft_preferences.prefer_online_exams:
        return DimensionResult(None, False, "Exam-format preference not specified.")
    if assessment is None:
        return DimensionResult(
            None, True, "No exam-format information is available for this section yet."
        )

    format_value = assessment.final_format or assessment.midterm_format
    if format_value is None:
        return DimensionResult(None, True, "Exam format wasn't specified in the available syllabus.")

    exam_label = "final exam" if assessment.final_format else "midterm exam"
    source = f" (source: {assessment.syllabus.source_document})" if assessment.syllabus else ""
    score = _EXAM_FORMAT_SCORES.get(format_value)
    if format_value == "none":
        detail = f"This course has no {exam_label} according to the syllabus{source}."
    else:
        detail = f"The {exam_label} is {format_value.replace('_', ' ')} according to the syllabus{source}."
    return DimensionResult(score, True, detail)


def compute_features(
    section: Section,
    parsed: ParsedRequirement,
    grade_stats: GradeDistributionStats | None,
    assessment: AssessmentMetadata | None = None,
) -> dict[str, DimensionResult]:
    return {
        "professor_rating": _professor_rating(section),
        "historical_grades": _historical_grades(grade_stats),
        "delivery_mode_preference": _delivery_mode_preference(section, parsed),
        "difficulty_preference": _grading_ease(section, parsed),
        "campus_days_preference": _campus_days(section, parsed),
        "exam_preference": _exam_preference(assessment, parsed),
    }
